export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILURE = 'SIGN_IN_USER_FAILURE';

export const POST_API_REQUEST = 'POST_API_REQUEST';
export const POST_API_SUCCESS = 'POST_API_SUCCESS';
export const POST_API_FAILURE = 'POST_API_FAILURE';

export const YOUTUBE_USER_REQUEST = 'YOUTUBE_USER_REQUEST';
export const YOUTUBE_USER_SUCCESS = 'YOUTUBE_USER_SUCCESS';
export const YOUTUBE_USER_FAILURE = 'YOUTUBE_USER_FAILURE';

export const YOUTUBE_DATA_REQUEST = 'YOUTUBE_DATA_REQUEST';
export const YOUTUBE_DATA_SUCCESS = 'YOUTUBE_DATA_SUCCESS';
export const YOUTUBE_DATA_FAILURE = 'YOUTUBE_DATA_FAILURE';

export const USER_LIKE_REQUEST = 'USER_LIKE_REQUEST';
export const USER_LIKE_SUCCESS = 'USER_LIKE_SUCCESS';
export const USER_LIKE_FAILURE = 'USER_LIKE_FAILURE';

export const USER_DISLIKE_REQUEST = 'USER_DISLIKE_REQUEST';
export const USER_DISLIKE_SUCCESS = 'USER_DISLIKE_SUCCESS';
export const USER_DISLIKE_FAILURE = 'USER_DISLIKE_FAILURE';

export const USER_COMMENT_REQUEST = 'USER_COMMENT_REQUEST';
export const USER_COMMENT_SUCCESS = 'USER_COMMENT_SUCCESS';
export const USER_COMMENT_FAILURE = 'USER_COMMENT_FAILURE';
export const USER_COMMENT_DELETE_SUCCESS = 'USER_COMMENT_DELETE_SUCCESS';

export const PUSH_PACKAGE_REQUEST = 'PUSH_PACKAGE_REQUEST';
export const PUSH_PACKAGE_SUCCES = 'PUSH_PACKAGE_SUCCES';
export const PUSH_PACKAGE_FAILURE = 'PUSH_PACKAGE_FAILURE';

export const RECHARGE_REQUEST = 'RECHARGE_REQUEST';
export const RECHARGE_SUCCESS = 'RECHARGE_SUCCESS';
export const RECHARGE_FAILLURE = 'RECHARGE_FAILLURE';

export const MAKE_OWN_BUNDLE_SUCCESS = 'RECHARGE_SUCCESS';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'; //for login screen
export const LOGIN_USER_UPDATE = 'LOGIN_USER_UPDATE'; //for login screen

export const SAVA_DATA_OF_USER = 'SAVA_DATA_OF_USER'; //for login screen
export const SET_ALARM = 'SET_ALARM';
